version: "3.7"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./.volumes/clickhouse:/var/lib/clickhouse
      - ./migrations:/docker-entrypoint-initdb.d

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
      - "8081:80"
    environment:
      - CH_HOST=clickhouse:8123
      - CH_NAME=default

  app:
    image: a41ventures/peekd:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "9090:9090/tcp"
      - "9090:9090/udp"
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - clickhouse