version: "3.7"
services:
  clickhouse:
    image: yandex/clickhouse-server
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=default
    hostname: clickhouse
    ports:
      - "8123:8123"
    volumes:
      - ./.volumes/clickhouse:/var/lib/clickhouse

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: clickhouse-tabix-web-client
    restart: always
    ports:
      - "8081:80"
    environment:
      - CH_HOST=clickhouse:8123
